name: README with Todoist

on:
    workflow_dispatch:
    schedule:
        # Runs every minute; change it as you like
        - cron: "* * * * *"

jobs:
    update-readme:
        name: Update todoist stats
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: SiddharthShyniben/todoist-readme@1.3.0
              with:
                  TODOIST_API_KEY: ${b959675092d2cdb40f2ca75fde8a81e16a7f73ee}
  
